name: Helm Delete Old Packages

on:
  push:
    branches:
      - gh-pages

jobs:
  delete_old_packages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Install PyYAML
      run: python -m pip install PyYAML

    - name: Install Helm
      run: |
        sudo snap install helm --classic

    - name: Delete old packages and update Helm index
      run: python .github/workflows/helm_delete_old_packages.py

    - name: Update Helm index
      run: |
        helm repo index snapshot --url https://epam.github.io/edp-helm-charts/snapshot

    - name: Commit and push changes
      id: commit_and_push
      run: |
        git config --local user.email "SupportEPMD-EDP@epam.com"
        git config --local user.name "edp-bot"
        git add .
        git diff-index --quiet HEAD || git commit -m "Delete old packages of Helm charts" || (echo "No changes" && exit 0)
        git push